### ISSUE TITLE
Influxdb connector crashes when Grafana is opened.

### ISSUE THREAD

**Issue by rai20** [eclipse/kuksa.cloud#137] opened 2019-11-19 15:54 UTC
The influxdb connector deployed on the Azure cloud crashes when grafana is opened.
Below is the log

2019-11-19 13:43:20.437  INFO 1 --- [ntloop-thread-0] o.e.k.h.influxdb.InfluxDBClient          : Generated timestamp: 1574171000437 for message with sender: 4500
2019-11-19 13:43:20.485  INFO 1 --- [ntloop-thread-0] o.e.k.h.influxdb.InfluxDBClient          : Generated timestamp: 1574171000485 for message with sender: 4500
2019-11-19 13:43:20.531 ERROR 1 --- [pool-1-thread-1] org.influxdb.impl.BatchProcessor         : Batch could not be sent. Data will be lost

org.influxdb.InfluxDBIOException: java.net.ConnectException: Failed to connect to influxdb.hono/10.0.104.156:8086
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:800) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:455) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:321) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:269) ~[influxdb-java-2.14.jar!/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.ConnectException: Failed to connect to influxdb.hono/10.0.104.156:8086
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at org.influxdb.impl.BasicAuthInterceptor.intercept(BasicAuthInterceptor.java:22) ~[influxdb-java-2.14.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:42) ~[influxdb-java-2.14.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144) ~[logging-interceptor-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.11.0.jar!/:na]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar!/:na]
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:788) ~[influxdb-java-2.14.jar!/:na]
	... 10 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245) ~[okhttp-3.11.0.jar!/:na]
	... 38 common frames omitted

2019-11-19 13:43:20.538  INFO 1 --- [ntloop-thread-0] o.e.k.h.influxdb.InfluxDBClient          : Generated timestamp: 1574171000538 for message with sender: 4500
2019-11-19 13:43:20.585  INFO 1 --- [ntloop-thread-0] o.e.k.h.influxdb.InfluxDBClient          : Generated timestamp: 1574171000585 for message with sender: 4500
2019-11-19 13:43:20.633 ERROR 1 --- [pool-1-thread-1] org.influxdb.impl.BatchProcessor         : Batch could not be sent. Data will be lost

org.influxdb.InfluxDBIOException: java.net.ConnectException: Failed to connect to influxdb.hono/10.0.104.156:8086
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:800) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:455) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:321) ~[influxdb-java-2.14.jar!/:na]
	at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:269) ~[influxdb-java-2.14.jar!/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.ConnectException: Failed to connect to influxdb.hono/10.0.104.156:8086
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at org.influxdb.impl.BasicAuthInterceptor.intercept(BasicAuthInterceptor.java:22) ~[influxdb-java-2.14.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:42) ~[influxdb-java-2.14.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144) ~[logging-interceptor-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.11.0.jar!/:na]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar!/:na]
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:788) ~[influxdb-java-2.14.jar!/:na]
	... 10 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129) ~[okhttp-3.11.0.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245) ~[okhttp-3.11.0.jar!/:na]
	... 38 common frames omitted

**Comment by rai20** [comment] 2019-11-22 09:11
@selobosi @unly @eriksven  - Could you guys look into this on priority, this causes a lot of issue during demos. Thank you

**Comment by selobosi** [comment] 2019-11-26 16:41
I'll have a look and try to have the connector re-create the connection to InfluxDB after it failed.

**Comment by selobosi** [comment] 2019-11-27 11:39
I tried to reproduce the problem locally by adding a unit test for InfluxDBClient that attempts to connect to a port that no server listens to. I'm thereby able to reproduce the InfluxbDBIOException and its cause (the ConnectException). However, I could not get InfluxDBClient into a state where it did stop trying to reconnect to the InfluxDB service (I used a loop to send 100 batches with 100ms of waiting between each batch and every batch did yield a ConnectException). I.e. I would assume that if a server becomes available again on the port, the connection attempt will succeed eventually.

@rai20 Are you able to reproduce the problem again when opening Grafana while data is being sent?

**Comment by selobosi** [comment] 2019-11-28 08:51
It might be necessary to open multiple connections to InfluxDB (e.g. Grafana that updates every 5 seconds, InfluxDB app).

We also saw that hono-adapter-mqtt continued to receive data, but was not able to forward it because hono-influxdb-connector ceased to listen to hono telemetry.

**Comment by selobosi** [comment] 2019-12-19 12:43
So it seems like hono-influxdb-connector (silently, i.e. with no log output) drops/looses/... the connection to Hono. That's the point where we'd need to continue our investigation. The current work-around is to restart the influxdb-connector pod.

**Comment by selobosi** [comment] 2020-01-30 10:10
Has been fixed with PR #151

**Closed by selobosi** 2020-01-30 10:10 UTC
