### ISSUE TITLE
Appstore does not consider the version of the app and matches only the app names

### ISSUE THREAD

**Issue by rai20** [eclipse/kuksa.cloud#45] opened 2019-03-15 12:06 UTC
If there are multiple Software Modules in Hawkbit with the same name but different version, While installing the App from appstore all the versions of the apps are deployed.

I think the FIQL needs to be used to select the specific version of the app.
eg : /rest/v1/softwaremodules?q=name%3D%3Dexample_app%3Bversion%3D%3D1.0.0

see: https://www.eclipse.org/hawkbit/apis/mgmt/softwaremodules/

**Comment by trademkose** [comment] 2019-05-28 11:30
@selobosi @rai20 Could we close this issue? It was fixed with commit #52.

**Comment by selobosi** [comment] 2019-05-28 11:39
If @rai20 is fine with closing the issue, I would update the cloud deployment and close the issue thereafter. Or do you need an up-to-date cloud deployment to verify that the issue is resolved, @rai20 ?

**Comment by rai20** [comment] 2019-05-28 11:42
Can be closed for now. I haven't tested this tough. Will be re-opened if the issue persists.

**Comment by selobosi** [comment] 2019-05-28 14:57
The changes are deployed in the appstacle cluster.

**Closed by selobosi** 2019-05-28 14:57 UTC
